// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBH3I1b2Pruro33WAI8e985jc5KZdJxvyg',
    appId: '1:704429265979:web:a3e4389653a3146974781e',
    messagingSenderId: '704429265979',
    projectId: 'flutter-e57de',
    authDomain: 'flutter-e57de.firebaseapp.com',
    storageBucket: 'flutter-e57de.appspot.com',
    measurementId: 'G-CZ43K8435E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwV-1qoGdkdQ9Aul6sN-_8r2AhxTv_sTo',
    appId: '1:704429265979:android:4f47974699c4192974781e',
    messagingSenderId: '704429265979',
    projectId: 'flutter-e57de',
    storageBucket: 'flutter-e57de.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeUgL55E9hun5eOBIXqKz3sF5guY1eeQI',
    appId: '1:704429265979:ios:2f787529cf881bd774781e',
    messagingSenderId: '704429265979',
    projectId: 'flutter-e57de',
    storageBucket: 'flutter-e57de.appspot.com',
    iosClientId: '704429265979-3elqld4c0jnb2ssv4bvr6d410cek8c8k.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeUgL55E9hun5eOBIXqKz3sF5guY1eeQI',
    appId: '1:704429265979:ios:2f787529cf881bd774781e',
    messagingSenderId: '704429265979',
    projectId: 'flutter-e57de',
    storageBucket: 'flutter-e57de.appspot.com',
    iosClientId: '704429265979-3elqld4c0jnb2ssv4bvr6d410cek8c8k.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTp',
  );
}
